spring:
    profiles:
      active:
      - dev
---
spring:
   profiles: dev
   application: 
       name: microservicecloud-config-yangjin-dev
---
spring:
   profiles: test
   application: 
       name: microservicecloud-config-yangjin-test
  