spring:
    profiles:
      active:
      - dev
---
server:
  port:  8001
spring:
   application:
     profiles: dev
     name: microservicecloud-config-dept-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8            
      username: root
      password: 123456
      dbcp2:
       min-idle: 5
       initial-size: 5
       max-total: 5                                  
       max-wait-millis: 200


mybatis:
  config-location: classpath:mapper/mybatis.cfg.xml
  type-aliases-package: com.yangjin.springcloud.entites
  mapper-locations: classpath*:mapper/*Mapper.xml 

eureka:
  client:
   service-url:
          defaultZone: http://eureka7001.com:7001/eureka
  instance: 
    instance-id: dept8001.com
    prefer-ip-address: true                         

info:
  app.name: yangjin-microservicecloud-springcloudconfig01   
  company.name: www.yangjin.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port:  8001
spring:
   application:
     profiles: test
     name: microservicecloud-config-dept-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=utf8            
      username: root
      password: 123456
      dbcp2:
       min-idle: 5
       initial-size: 5
       max-total: 5                                  
       max-wait-millis: 200


mybatis:
  config-location: classpath:mapper/mybatis.cfg.xml
  type-aliases-package: com.yangjin.springcloud.entites
  mapper-locations: classpath*:mapper/*Mapper.xml 

eureka:
  client:
   service-url:
          defaultZone: http://eureka7001.com:7001/eureka
  instance: 
    instance-id: dept8001.com
    prefer-ip-address: true                         

info:
  app.name: yangjin-microservicecloud-springcloudconfig02   
  company.name: www.yangjin.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
